### ISSUE TITLE
인자 갯수 제한

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#28]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/controllers/orders.controller.js#L25

인자 갯수가 4개를 초과 하는 경우 객체로 넘겨주시면 좋습니다.

**Comment by cchoseonghun** [comment]
orderInfo 와 같은 Object를 따로 만들어 (가공하여) 전달하는게 좋은지?
req.body 그대로 넘기는게 좋은지? -> 이 경우 req.params, req.query, res.locals 같은 데이터를 활용하기 힘듦

**Comment by cchoseonghun** [comment]
적용 완료
