### ISSUE TITLE
백엔드 / 프론트엔드 분리 할경우

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#29]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/controllers/reviews.controller.js#L13

### 백엔드 / 프론트엔드 분리 할경우
위처럼 render 에 백엔드가 개입해서 db 의 값을 사용하는것은 좋지 않습니다.
백엔드는 json 으로만 응답하도록 해주세요.

**Comment by cchoseonghun** [comment]
res.render를 쓰는 경우는 모두 페이지 이동으로 제한.
데이터가 필요할 경우 
페이지 이동한 후에 해당 페이지에서 
만들어진 api를 통해 데이터 받아 사용

**Comment by cchoseonghun** [comment]
output 기능과 api 기능 분리로 해결
