### ISSUE TITLE
변수명

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#30]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/controllers/users.controller.js#L9

true, false 와 같은 결과가 나오는 변수/함수는 isAdmin 과 같이 명확한 이름의 함수를 써주세요.
이후에 admin 에 진짜 admin  정보를 넣어야 할때 혼란스럽게 됩니다

**Comment by cchoseonghun** [comment]
db 컬럼명 admin -> isAdmin으로 변경 후 
admin인 값 모두 찾아 isAdmin으로 변경 예정
sequelize migration 파일 공유해서 적용이 어렵지 막상 찾아 바꾸는건 쉬울듯

**Comment by cchoseonghun** [comment]
적용 완료
