### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#32]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/services/orders.service.js#L13

```node
    return allLists.map(orders => {
      const { 응답에 필요없는 properties, ..output} = orders
      return orders
    }).sort((prev, next) => {
      return prev.createdAt - next.createdAt;
    });
```

- a, b 와 같이 의미없는 변수는 사용을 지양합니다.
- allLists 에서 가져온 값들이 전부 쓸모가 없다면 select 할때부터 제외 하면 더욱 깔끔한 코드가 됩니다.
- 응답에 필요없는 프로퍼티들을 제거하도록 일단 작성해보았습니다.

**Comment by cchoseonghun** [comment]
@haebeenjo 확인 후 코멘트

**Comment by cchoseonghun** [comment]
#54 수정 완료
