### ISSUE TITLE
값을 알아 볼수 있는 값으로 사용

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#33]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/services/orders.service.js#L34

1, 2 이런 status 는 나중에 무엇을 의미하는지 알기가 어려워져 유지보수가 힘들어지고, 버그의 원인이 되는경우가 많습니다.

**Comment by cchoseonghun** [comment]
어떤 상태인지, 여러 과정 중 몇 단계인지에 대한 정보를 동시에 알려줄 수 있게 하려면 어떻게 하면 좋을지?
|코드|상태|
|-|-|
|0|대기 중|
|0|대기 중|
|0|대기 중|

**Comment by cchoseonghun** [comment]
typescript의 enum을 통해 해결할 수 있지 않을까

**Comment by cchoseonghun** [comment]
https://4sii.tistory.com/384
