### ISSUE TITLE
중복 조건문 지양

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#34]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/services/orders.service.js#L68

만약 createResult 가 0 이라면 return 이 없어 로직상도 버그가 생길 확률이 있습니다.
아래 처럼 시도해보면 어떨까 합니다. (사고의 흐름대로 평면적으로 가는것이 가장 알아보기 쉽습니다.)

```node
    if (createResult === 0) {
      return {code: 400, message; '에러'}
    }

   const pointDeductResult = await this.ordersRepository.pointDeduct(ownerId, process.env.ORDER_PRICE);
   if (!pointDeductResult) {
         return {code: 400, message; '에러'}
   }
  return { code: 201, message: '주문에 성공하였습니다.' };
```

**Comment by cchoseonghun** [comment]
if문 안의 if문과 같은 중복 조건문 지양
if문으로 바로 해당되지 않는 경우에 대해 처리해준 뒤 진행되게끔 해주는게 좋다.

해당사항과 비슷한 로직들 찾아서 바로 수정 예정

**Comment by cchoseonghun** [comment]
#47 에서 적용완료. 이후 모든 코드들에서 찾아 적용 예정
