### ISSUE TITLE
유효성 판단은 미리 하고 에러처리.

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#35]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/services/orders.service.js#L85

먼저 유효성 판단 후 실패하면 에러처리 하고 계속 밑으로 로직을 이어나가는것이 좋습니다.
가장 아래오는 코드는 정상 처리여야 좋습니다.

```node
    if (result[0] === 0) {
        return { code: 500, message: '주문 상태 변경 실패' };
    }

    return { code: 200, message: '수정 완료' };

```

**Comment by cchoseonghun** [comment]
#34 와 같은 맥락.
정상코드는 제일 아래 위치하는게 베스트
유효성 판단에서 실패에 대한 처리는 바로 명시 및 처리해준 뒤 
정상적인 상황이 밑으로 이어지게 유도
