### ISSUE TITLE
함수명

### ISSUE THREAD

**Issue by noggong** [9hezo/save_my_keyboard#40]
https://github.com/9hezo/save_my_keyboard/blob/3d43b9d533b095ba96c5257ff68d7cf3e5183906/app/src/repositories/orders.repository.js#L42

이 함수명으로 이 함수의 기능을 유추 할수 없습니다.
예를 들면 getOrderWaiting 

이런식으로 명확하게 용도를 알수 있는 함수가 좋습니다.

**Comment by cchoseonghun** [comment]
admin에서의 재활용성도 고려해 재작명 필요
